## Eigenvalues and eigenvectors

http://www.physics.utah.edu/~detar/lessons/python/numpy_eigen/node1.html

![alt text](http://www.physics.utah.edu/~detar/lessons/python/numpy_eigen/img1.png)

![alt text](http://www.physics.utah.edu/~detar/lessons/python/numpy_eigen/img2.png "Title")



In [1]:
import numpy as np
from numpy import linalg as LA
A = np.array([[1,2,3],[3,2,1],[1,0,-1]])
print (A)



[[ 1  2  3]
 [ 3  2  1]
 [ 1  0 -1]]


In [2]:
LA.eig?

In [2]:
w, v = LA.eig(A)
print(w)

print(v)

[ 4.31662479e+00 -2.31662479e+00  1.93041509e-17]
[[ 0.58428153  0.73595785  0.40824829]
 [ 0.80407569 -0.38198836 -0.81649658]
 [ 0.10989708 -0.55897311  0.40824829]]


In [3]:
# print out 1st column
u = v[:,0]
print(u)

[0.58428153 0.80407569 0.10989708]


In [4]:
lam = w[0]
print(lam)

4.3166247903554


In [5]:
A

array([[ 1,  2,  3],
       [ 3,  2,  1],
       [ 1,  0, -1]])

In [7]:
u

array([0.58428153, 0.80407569, 0.10989708])

In [6]:
print(np.dot(A,u))

[2.52212416 3.47089307 0.47438446]


In [7]:
print(lam*u)

[2.52212416 3.47089307 0.47438446]
