# matrix factorization using sklearn 

In [1]:
import numpy
from sklearn.decomposition import NMF

In [2]:
?NMF

In [2]:
R = [
     [5,3,0,1],
     [4,0,0,1],
     [1,1,0,5],
     [1,0,0,4],
     [0,1,5,4],
    ]
R = numpy.array(R)
R

array([[5, 3, 0, 1],
       [4, 0, 0, 1],
       [1, 1, 0, 5],
       [1, 0, 0, 4],
       [0, 1, 5, 4]])

In [3]:

model = NMF(n_components=2, init='random', random_state=0)
W = model.fit_transform(R)
H = model.components_

In [4]:
W

array([[0.        , 1.69547254],
       [0.        , 1.13044637],
       [1.38593123, 0.42353044],
       [1.08595617, 0.3165454 ],
       [2.01891156, 0.        ]])

In [5]:
H

array([[0.        , 0.32199795, 1.40668938, 2.58501889],
       [3.09992487, 1.17556787, 0.        , 0.85823043]])

In [6]:
numpy.dot(W,H)

array([[5.25583751, 1.99314304, 0.        , 1.45510614],
       [3.50429883, 1.32891643, 0.        , 0.97018348],
       [1.31291255, 0.9441558 , 1.94957474, 3.94614513],
       [0.98126695, 0.72179626, 1.52760301, 3.0788861 ],
       [0.        , 0.65008539, 2.83998144, 5.21892451]])